### ISSUE TITLE
Feature request: Add password items to Shared Folder

### ISSUE THREAD

**Issue by ghost** [schubergphilis/lastpasslib#6]
Thank you for the project! It looks very useful. Do you think it would be possible to add a feature to be able to add password items to a shared folder?

**Comment by costastf** [comment]
Hi @stevek123 , sorry i have missed this, I was not watching the project 😳 . Would you mind elaborating a bit on what you mean with this? Do you mean move a password from a non shared folder (personal) to a shared folder or create a new password on a shared folder altogether? The library only supports passive actions (read only) for now on purpose so there is no chance of corruption but we are thinking of adding a few active features. Once you elaborate a bit i might be able to tell you whether it can be implemented.

**Comment by ghost** [comment]
Hi @costastf! Thank you for getting back to me! :) The basic need for me would be to be able to create a brand new password directly into a shared folder. The use case for it would be to have the code in a pipeline as an automation. There is a [go library](https://github.com/ansd/lastpass-go) variant that seemingly can do it, but I would like to use Python for it. It would be an extra "nice to have" to be able to update or delete these shared password items as well, not just read them, but that's really just something extra, I'm happy if I could already create password items with a python lib in a shared folder directly. Does that makes sense?

**Comment by costastf** [comment]
Hi @stevek123 , yeah it does make sense. A colleague of mine is working on some active parts for the library and I have made him aware of this, i guess that it should be possible. Can't promise that it will be amazingly quick though.

**Comment by ghost** [comment]
@costastf That's okay, thank you for working on it :)

**Comment by costastf** [comment]
Hi @stevek123 , if you are still looking for this feature, the just released version from my colleague should cover your needs!

**Comment by ghost** [comment]
Hi @costastf, thank you so much!

**Comment by costastf** [comment]
I appreciate it, but thanks should go to Yorick that implemented everything!
